### ISSUE TITLE
Cedarview version

### ISSUE THREAD

**Issue by ghost** [th0ma7/synology#1] opened 2020-01-23 13:37 UTC
Hi
Is any chance to you compile for me and your repo Tvheadend for platform Cedarview ? I need file spk please....

**Comment by th0ma7** [comment] 2020-01-23 14:07
Source for issues related to spksrc is https://github.com/SynoCommunity/spksrc
Duplicate of https://github.com/SynoCommunity/spksrc/issues/3863

**Closed as completed by th0ma7** 2020-01-23 14:07 UTC

**Comment by ghost** [comment] 2020-01-23 14:09
But it is old version... but i want version 4.3
